// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using livrariaApi.Context;

namespace livrariaApi.Migrations
{
    [DbContext(typeof(ProdutoContext))]
    [Migration("20210721120132_produtoPC")]
    partial class produtoPC
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("livrariaApi.Entity.ProdutoCesta", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HD")
                        .HasColumnName("HD")
                        .HasColumnType("int");

                    b.Property<string>("MarcaProduto")
                        .HasColumnName("MarcaProduto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemoriaRam")
                        .HasColumnName("MemoriaRam")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .HasColumnName("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeProduto")
                        .HasColumnName("NomeProduto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlacaMae")
                        .HasColumnName("PlacaMae")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProdutoId");

                    b.ToTable("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
